config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/' => 'pages#index'
  get '/sobre' => 'pages#about'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
    belongs_to :student
    belongs_to :course

    validates :student, presence: true
    validates :course, presence: true
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :classrooms

	validates :name, presence: true
	validates :description, presence: true
	validates :status, presence: true

	def status_option
        status_option = case status
        when 0
            'Inativo'
        when 1
            'Ativo'
        end
    end
end

app/models/student.rb
class Student < ActiveRecord::Base
    has_many :classrooms

    validates :name, presence: true
    validates :status, presence: true

    def semester
        year = Time.now.year.to_s
        year = year[2..3]
        month = Time.now.month
        if month < 7
            semesterNumber = '1'
        else
            semesterNumber = '2'
        end
        semester = year << semesterNumber
        return semester
    end

    def studentNumber
        studentLast = Student.maximum(:id).next
        studentID = studentLast.to_s

        if studentID.size == 1
            studentNumber = '0000' << studentID
        elsif studentID.size == 2
            studentNumber = '000' << studentID
        elsif studentID.size == 3
            studentNumber = '00' << studentID
        elsif studentID.size == 4
            studentNumber = '0' << studentID
        elsif studentID.size == 3
            studentNumber = studentID
        end

        return studentNumber
    end

    after_initialize do
        if self.new_record?
            register = semester << studentNumber
            self.register_number = register
        end
    end

    def status_option
        status_option = case status
        when 1
            'Matriculado'
        when 2
            'Formado'
        when 3
            'Transferido'
        when 4
            'Cancelado'
        when 5
            'Jubilado'
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @courses = Course.all
        @students_total = Student.count
    end

    def about

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/admin/classrooms/_list_courses.erb
<table class="index_table index">
    <tr>
        <th>Curso</th>
        <th>Status</th>
    </tr>
    <% courses.each do |c| %>
    <tr>
        <td><a href="/admin/courses/<%=c.id%>"><%=c.name%></a></td>
        <td><%=c.status_option%></td>
    </tr>
    <% end %>
</table>

app/views/admin/courses/_show.erb
<h2>Courses</h2>

<h3><%=@course.name%></h3>
<p><%=@course.description%></p>
<h3><strong>Status:</strong> <%=@course.status_option%></h3>

<h2>Estudantes matriculados neste curso</h2>
<ul>
    <% @classroom.each do |s| %>
    <li><a href="/admin/students/<%=s.student.id%>"><%=s.student.name%></a></li>
    <%end%>
</ul>

app/views/admin/students/_show.erb
<h2>Student</h2>

<h3><%=@student.name%></h3>
<h3><strong>Register Number:</strong> <%=@student.register_number%></h3>
<h3><strong>Status:</strong> <%=@student.status_option%></h3>

<h2>Cursos deste estudante</h2>
<ul>
    <%Classroom.where(student: @student.id).each do |c|%>
    <li><a href="/admin/courses/<%=c.course.id%>"><%=c.course.name%></a></li>
    <%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

<title>Repense | Ensino a Distância</title>

<%= stylesheet_link_tag    'bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag    'main', media: 'all', 'data-turbolinks-track' => true %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
<%= csrf_meta_tags %>

<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><span class="fa fa-graduation-cap"></span> REPENSE - Ensino a Distância</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/sobre" title="Sobre">Sobre</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <%=yield%>

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; <strong>Repense</strong> <%=Time.now.year%></p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <%= javascript_include_tag 'jquery', 'data-turbolinks-track' => true %>

    <!-- Bootstrap Core JavaScript -->
    <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => true %>
    
    <%= javascript_include_tag 'main', 'data-turbolinks-track' => true %>

</body>

</html>

app/views/pages/about.html.erb
<div class="row">
	<div class="col-md-12">
		<hr>
		<h1>Sobre</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras id leo id justo blandit vestibulum. Nullam aliquet nunc nec nibh consectetur laoreet. Sed id metus ac tellus malesuada lacinia. Vestibulum in dictum ligula. Ut ex lectus, tempus id justo sed, tempus dictum quam. Vestibulum eu nunc vitae mi commodo porttitor sit amet in nulla. Vestibulum maximus lacus eu dictum imperdiet. Cras a aliquet metus. Sed nec augue vitae ligula egestas maximus. Nulla aliquet lectus at nulla tincidunt, a molestie nulla sagittis. Pellentesque non faucibus odio, ut malesuada felis. Quisque velit lacus, feugiat at enim vitae, viverra ultrices risus. Duis urna ligula, eleifend et fringilla eget, interdum hendrerit turpis. Pellentesque interdum quam nec faucibus fringilla.</p>

		<p>Vestibulum non lacinia magna. Integer tristique iaculis metus eu tempus. Aenean erat neque, sodales quis convallis a, pellentesque non orci. Donec mollis commodo vehicula. Nunc consectetur consequat risus sed elementum. Integer fringilla mi id mollis maximus. Ut ornare interdum tincidunt. Praesent euismod egestas posuere.</p>

		<p>Sed sapien massa, accumsan vitae venenatis ultrices, vulputate ut neque. Praesent orci diam, dictum vel eros ac, iaculis sodales tortor. Sed eu orci sit amet tellus consectetur cursus id nec leo. Morbi ac rhoncus neque. Cras elementum purus quis interdum tempus. Nunc vestibulum, ipsum nec condimentum congue, odio urna vehicula magna, porta convallis quam orci at lacus. Sed commodo, eros ac laoreet maximus, libero orci molestie orci, ut dapibus lacus augue ac leo. Maecenas suscipit hendrerit est id dignissim. Morbi nibh nunc, congue quis iaculis ut, pellentesque eu massa. Nulla mattis orci odio, tincidunt sodales purus tempor tempus. Phasellus in fringilla elit, et hendrerit elit.</p>

		<p>Nulla sollicitudin tellus vel dolor eleifend, at lobortis elit convallis. Praesent sit amet augue dignissim, viverra est ut, vehicula elit. Suspendisse egestas, diam in pulvinar varius, nibh tortor interdum ex, ut ullamcorper leo lectus sed sapien. Aliquam lacinia felis arcu, vitae vehicula dui molestie non. Sed id massa varius, commodo nisl et, efficitur tellus. Vivamus sollicitudin sapien et ante iaculis lacinia. Vestibulum ornare vel leo eu faucibus. Nulla maximus varius ex. Fusce et arcu id urna ullamcorper interdum non in elit.</p>

		<p>Suspendisse bibendum est eu tempor laoreet. Morbi interdum sapien neque, eu cursus nulla tempus ut. Suspendisse urna metus, egestas et justo in, vulputate auctor dui. Cras sodales blandit metus, sit amet condimentum nulla laoreet eget. Phasellus faucibus diam nec sem blandit, et sollicitudin nisi viverra. Morbi sit amet purus felis. Suspendisse potenti. Duis ac odio tincidunt, consequat mauris sit amet, consequat lorem. Phasellus sed orci felis. Sed posuere malesuada diam, ut ullamcorper erat luctus ut. Vestibulum sed porta quam. Donec ullamcorper, dolor a condimentum blandit, ligula magna luctus dui, ac commodo ligula massa eu nulla.</p>
	</div>
</div>

app/views/pages/index.html.erb
<div class="row">
    <div class="col-md-12">
        <hr>
        <div class="jumbotron">
            <h1>Saudações da Repense</h1>
            <p>No momento temos <%=@students_total%> alunos cadastrados.</p>
            <p><%=link_to "Conheça-nos", sobre_path, class: "btn btn-primary btn-lg", role: "button"%></p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <img src="http://lorempixel.com/image_output/business-q-c-640-480-6.jpg" class="img-responsive" alt="Image">
    </div>
    <div class="col-md-6">
        <h1><span class="fa fa-file"></span> Cursos Disponíveis</h1>
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            <% @courses.each do |c| %>
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="heading<%=c.id%>">
                    <h4 class="panel-title">
                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%=c.id%>" aria-expanded="false" aria-controls="collapse<%=c.id%>">
                            <span class="fa fa-caret-right"></span> <%=c.name%>
                        </a>
                    </h4>
                </div>
                <div id="collapse<%=c.id%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<%=c.id%>">
                    <div class="panel-body">
                        <%=c.description%>
                    </div>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>